common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 6
  host: localhost
  username: root
  password: root
  # socket: /var/lib/mysql/mysql.sock

development:
  <<: *common
  database: xemayviet_development

test:
  <<: *common
  database: xemayviet_test

staging:
  <<: *common
  database: xemayviet_staging

production:
  <<: *common
  database: xemayviet
