common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 6
  host: localhost
  username: root
  password: root
  # socket: /var/lib/mysql/mysql.sock

development:
  <<: *common
  database: xmv_development

test:
  <<: *common
  database: xmv_test

staging:
  <<: *common
  database: xmv_staging

production:
  <<: *common
  database: xmv
